# Generated by Django 4.1.5 on 2023-01-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part_per_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citis', models.CharField(max_length=30, verbose_name='Название городов')),
                ('city_collum_1', models.CharField(max_length=30, verbose_name='Город колонка 1')),
                ('salary_collum_1', models.IntegerField(verbose_name='количество вакансий в городе колонка 1')),
                ('part_collum_1', models.CharField(max_length=4, verbose_name='Доля 1')),
                ('city_collum_2', models.CharField(max_length=30, verbose_name='Город колонка 2')),
                ('vacancies_collum_2', models.IntegerField(verbose_name='Количество вакансий колонка 2')),
                ('part_collum_2', models.CharField(max_length=15, verbose_name='Доля 2')),
            ],
            options={
                'verbose_name': 'количество вакансий по городу',
                'verbose_name_plural': 'количество вакансий по городам',
            },
        ),
        migrations.CreateModel(
            name='Salaries_in_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('all_professions', models.IntegerField(verbose_name='Доход всех профессий')),
                ('it_manager', models.IntegerField(verbose_name='Доход менеджера IT-проекта')),
            ],
            options={
                'verbose_name': 'доход по году',
                'verbose_name_plural': 'доход по годам',
            },
        ),
        migrations.CreateModel(
            name='Salary_in_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citis', models.CharField(max_length=30, verbose_name='Название городов')),
                ('city_collum_1', models.CharField(max_length=15, verbose_name='Город колонка 1')),
                ('salary_collum_1', models.IntegerField(verbose_name='Доход всех профессий колонка 1')),
                ('city_collum_2', models.CharField(max_length=15, verbose_name='Город колонка 2')),
                ('salary_collum_2', models.IntegerField(verbose_name='Доход всех профессий колонка 2')),
            ],
            options={
                'verbose_name': 'доход по городу',
                'verbose_name_plural': 'доход по городам',
            },
        ),
        migrations.CreateModel(
            name='Skill_in_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('skill', models.CharField(max_length=50, verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Навык по году',
                'verbose_name_plural': 'Навыки по годам',
            },
        ),
        migrations.CreateModel(
            name='Vacancies_in_year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('all_professions', models.IntegerField(verbose_name='Доля всех профессий')),
                ('it_manager', models.IntegerField(verbose_name='Доля менеджера IT-проекта')),
            ],
            options={
                'verbose_name': 'количества вакансий по году',
                'verbose_name_plural': 'количества вакансий по годам',
            },
        ),
    ]
